// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmD16-48xk0bOglSjPfEofel7t9KmqlHo',
    appId: '1:1058377586337:web:eee8ddf9eb805fe1f382e0',
    messagingSenderId: '1058377586337',
    projectId: 'bookly-app-1323f',
    authDomain: 'bookly-app-1323f.firebaseapp.com',
    storageBucket: 'bookly-app-1323f.appspot.com',
    measurementId: 'G-02QD5TNS0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxWS-hM8I2z3AsuLTpT6qj2wlguGUfU-s',
    appId: '1:1058377586337:android:c329a83fe710f345f382e0',
    messagingSenderId: '1058377586337',
    projectId: 'bookly-app-1323f',
    storageBucket: 'bookly-app-1323f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcpJw2c0-8Lbty7dEc8bphIXwqtWFn9a0',
    appId: '1:1058377586337:ios:a3da3025c56457a2f382e0',
    messagingSenderId: '1058377586337',
    projectId: 'bookly-app-1323f',
    storageBucket: 'bookly-app-1323f.appspot.com',
    iosBundleId: 'com.example.myBookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcpJw2c0-8Lbty7dEc8bphIXwqtWFn9a0',
    appId: '1:1058377586337:ios:a3da3025c56457a2f382e0',
    messagingSenderId: '1058377586337',
    projectId: 'bookly-app-1323f',
    storageBucket: 'bookly-app-1323f.appspot.com',
    iosBundleId: 'com.example.myBookly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmD16-48xk0bOglSjPfEofel7t9KmqlHo',
    appId: '1:1058377586337:web:2a4e7bff085e5c66f382e0',
    messagingSenderId: '1058377586337',
    projectId: 'bookly-app-1323f',
    authDomain: 'bookly-app-1323f.firebaseapp.com',
    storageBucket: 'bookly-app-1323f.appspot.com',
    measurementId: 'G-KYJWG2LEYV',
  );
}
