// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeU3hwdXcpHDFS7O6kR5he7zYLnpv23rE',
    appId: '1:954652922597:web:70089c4c4f3d40d4773a0c',
    messagingSenderId: '954652922597',
    projectId: 'bookly-dc51c',
    authDomain: 'bookly-dc51c.firebaseapp.com',
    storageBucket: 'bookly-dc51c.appspot.com',
    measurementId: 'G-NKZHRQJPQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeaVMGvhx_F5SGkis4oBQ37pQ1PB5zrfA',
    appId: '1:954652922597:android:ffb0d4ddaf550fe4773a0c',
    messagingSenderId: '954652922597',
    projectId: 'bookly-dc51c',
    storageBucket: 'bookly-dc51c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2txcPCnE3DzOhxwS9mWZhIF3c0kzQ8yg',
    appId: '1:954652922597:ios:51ca85f13a4d55fd773a0c',
    messagingSenderId: '954652922597',
    projectId: 'bookly-dc51c',
    storageBucket: 'bookly-dc51c.appspot.com',
    iosBundleId: 'com.example.myBookly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2txcPCnE3DzOhxwS9mWZhIF3c0kzQ8yg',
    appId: '1:954652922597:ios:51ca85f13a4d55fd773a0c',
    messagingSenderId: '954652922597',
    projectId: 'bookly-dc51c',
    storageBucket: 'bookly-dc51c.appspot.com',
    iosBundleId: 'com.example.myBookly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeU3hwdXcpHDFS7O6kR5he7zYLnpv23rE',
    appId: '1:954652922597:web:9d2d0f1ff1e15fde773a0c',
    messagingSenderId: '954652922597',
    projectId: 'bookly-dc51c',
    authDomain: 'bookly-dc51c.firebaseapp.com',
    storageBucket: 'bookly-dc51c.appspot.com',
    measurementId: 'G-TTN46JBFB0',
  );
}
